version: "3.9"
services:
  vue:
    build: ./vue
    tty: true
    stdin_open: true
    command: yarn serve
    ports:
      - "8080:8080"
    volumes:
      - ./vue:/app

  rails-api:
    build: ./rails
    container_name: rails-api
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails:/myapp
      - /myapp/node_modules
      - public-data:/myapp/public
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql-db
    tty: true
    stdin_open: true
    # environment:
    #   WEBPACKER_DEV_SERVER_HOST: rails-webpacker

  # rails-webpacker:
  #   build: ./rails
  #   container_name: rails-webpacker
  #   volumes:
  #     - ./rails:/myapp
  #     - /myapp/node_modules
  #     - public-data:/myapp/public
  #   command: ./bin/webpack-dev-server
  #   environment:
  #     WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
  #   ports:
  #     - "3035:3035"

  mysql-db:
    image: mysql:8.0.27
    container_name: mysql-db
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
  bundle:
    driver: local
  public-data: